# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import turtle_soup_game_service_pb2 as turtle__soup__game__service__pb2


class TurtleSoupGameServiceStub(object):
    """clang-format off 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/turtle_soup_game_service.TurtleSoupGameService/Ping',
                request_serializer=turtle__soup__game__service__pb2.PingRequest.SerializeToString,
                response_deserializer=turtle__soup__game__service__pb2.PongResponse.FromString,
                )
        self.GenerateDialogue = channel.unary_unary(
                '/turtle_soup_game_service.TurtleSoupGameService/GenerateDialogue',
                request_serializer=turtle__soup__game__service__pb2.GenerateDialogueRequest.SerializeToString,
                response_deserializer=turtle__soup__game__service__pb2.GenerateDialogueResponse.FromString,
                )


class TurtleSoupGameServiceServicer(object):
    """clang-format off 
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDialogue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurtleSoupGameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=turtle__soup__game__service__pb2.PingRequest.FromString,
                    response_serializer=turtle__soup__game__service__pb2.PongResponse.SerializeToString,
            ),
            'GenerateDialogue': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDialogue,
                    request_deserializer=turtle__soup__game__service__pb2.GenerateDialogueRequest.FromString,
                    response_serializer=turtle__soup__game__service__pb2.GenerateDialogueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'turtle_soup_game_service.TurtleSoupGameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TurtleSoupGameService(object):
    """clang-format off 
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/turtle_soup_game_service.TurtleSoupGameService/Ping',
            turtle__soup__game__service__pb2.PingRequest.SerializeToString,
            turtle__soup__game__service__pb2.PongResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateDialogue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/turtle_soup_game_service.TurtleSoupGameService/GenerateDialogue',
            turtle__soup__game__service__pb2.GenerateDialogueRequest.SerializeToString,
            turtle__soup__game__service__pb2.GenerateDialogueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
