# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turtle_soup_game_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eturtle_soup_game_service.proto\x12\x18turtle_soup_game_service\"\r\n\x0bPingRequest\"\x0e\n\x0cPongResponse\"%\n\x08\x41IResult\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x82\x02\n\x17GenerateDialogueRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x37\n\nllm_engine\x18\x02 \x01(\x0e\x32#.turtle_soup_game_service.LLMEngine\x12\"\n\x1a\x63onversation_system_prompt\x18\x03 \x01(\t\x12%\n\x1dto_reply_for_general_question\x18\x04 \x01(\x08\x12\x0c\n\x04\x63hat\x18\x05 \x01(\t\x12\x15\n\rext_thread_id\x18\x06 \x01(\t\x12\x0f\n\x07\x65xt_uid\x18\x07 \x01(\t\x12\x14\n\x0c\x65xt_nickname\x18\x08 \x01(\t\"\x9a\x01\n\x18GenerateDialogueResponse\x12/\n\x03ret\x18\x01 \x01(\x0b\x32\".turtle_soup_game_service.AIResult\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x0c\n\x04\x63hat\x18\x03 \x01(\t\x12\x15\n\rext_thread_id\x18\x04 \x01(\t\x12\x0f\n\x07\x65xt_uid\x18\x05 \x01(\t*:\n\tLLMEngine\x12\n\n\x06OPENAI\x10\x00\x12\t\n\x05\x41ZURE\x10\x01\x12\n\n\x06GEMINI\x10\x02\x12\n\n\x06\x43LAUDE\x10\x03\x32\xed\x01\n\x15TurtleSoupGameService\x12W\n\x04Ping\x12%.turtle_soup_game_service.PingRequest\x1a&.turtle_soup_game_service.PongResponse\"\x00\x12{\n\x10GenerateDialogue\x12\x31.turtle_soup_game_service.GenerateDialogueRequest\x1a\x32.turtle_soup_game_service.GenerateDialogueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turtle_soup_game_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LLMENGINE']._serialized_start=548
  _globals['_LLMENGINE']._serialized_end=606
  _globals['_PINGREQUEST']._serialized_start=60
  _globals['_PINGREQUEST']._serialized_end=73
  _globals['_PONGRESPONSE']._serialized_start=75
  _globals['_PONGRESPONSE']._serialized_end=89
  _globals['_AIRESULT']._serialized_start=91
  _globals['_AIRESULT']._serialized_end=128
  _globals['_GENERATEDIALOGUEREQUEST']._serialized_start=131
  _globals['_GENERATEDIALOGUEREQUEST']._serialized_end=389
  _globals['_GENERATEDIALOGUERESPONSE']._serialized_start=392
  _globals['_GENERATEDIALOGUERESPONSE']._serialized_end=546
  _globals['_TURTLESOUPGAMESERVICE']._serialized_start=609
  _globals['_TURTLESOUPGAMESERVICE']._serialized_end=846
# @@protoc_insertion_point(module_scope)
